language: haxe
sudo: false

haxe:
- development
- 3.4.7
- 3.4.2

php:
- '7.1'

before_script: phpenv config-add phpconfig.ini


install:
- haxelib install all --always

script:
- haxe test.hxml
- neko test.n
- haxe testPHP.hxml
- php index.php
