language: haxe
sudo: true

haxe:
- development
- 3.4.7
- 3.4.2

before_install:
#install php 7.2 on ubuntu trusty
- sudo add-apt-repository ppa:ondrej/php -y
- sudo apt-get update
- sudo apt-get install -y php7.2


install:
- haxelib install all --always

script:
- haxe test.hxml
- neko test.n
- php -v
- haxe testPHP.hxml
- php index.php
